### ISSUE TITLE
Support schema creation

### ISSUE THREAD

**Issue by dongwq** [eugene-kamenev/orientdb-groovy#13]
how about support for index creation?

**Comment by eugene-kamenev** [comment]
I am thinking about whole schema not only managing index. But where is the best place to initialize it?

**Comment by dongwq** [comment]
I think it's better to use JPA style(using annotation) than grails way( defining in a mapping). There shoud be a init stategy, which do creating and check if created or schema consistence (based on code)

**Comment by eugene-kamenev** [comment]
Ok, what if this way: at compile time we create special initial method somewhere which you can call yourself at startup.

JPA way is also possible, but have not enough time right now to implement, contributions are welcome

**Comment by eugene-kamenev** [comment]
@dongwq can you please check this:
[GraphSchemaTransformationTest.groovy](https://github.com/eugene-kamenev/orientdb-groovy/blob/v0.1.1/src/test/groovy/com/github/eugene/kamenev/orient/schema/GraphSchemaTransformationTest.groovy)
If everything looks fine here, I will continue work for generating relationships from classes. Thanks.

**Comment by eugene-kamenev** [comment]
Implemented in v0.1.1

**Comment by dongwq** [comment]
@eugene-kamenev do you notice that _gradle test_ failed with exceptions as below:

```
Cannot open local storage 'test' with mode=rw
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage 'test' with mode=rw
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:244)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:249)
    at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.internalOpen(OPartitionedDatabasePool.java:140)
    at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:343)
    at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:313)
    at com.groovy.orient.document.OrientDocumentTransformationsTest.setup(OrientDocumentTransformationsTest.groovy:20)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'test' because it does not exist in path: test
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:185)
    ... 5 more

```

**Comment by eugene-kamenev** [comment]
gradle test runs fine, but through ide it fails, i am not sure what happened, but I belive gradle more. But will try to discover what actually happens.

**Comment by eugene-kamenev** [comment]
If you configure run test configuration with replacing default IDE Make task to "gradle build" then test is passing.
