### ISSUE TITLE
embedded object in vertex

### ISSUE THREAD

**Issue by dmunguia** [eugene-kamenev/orientdb-groovy#22]
Hey, love the library! thanks for the great work. 
I have a question, what's the best way of embedding an object into a vertex. I'm trying the following:

``` groovy
@OrientDocument
@CompileStatic
@EqualsAndHashCode
class Point {
    double latitude
    double longitude
}

@Vertex
@CompileStatic
class MyVertex {
    String name
    Point location

    static mapping = {
        location(type: OType.EMBEDDED)
    }
}
```

But I'm getting this exception when trying to create assign the `location` property with a new instance of `Point` :

``` groovy
MyVertex v = new MyVertex(
    name: theName,
    location: new Point(latitude: theLatitude, longitude: theLongitude)
)
```

```
groovy.lang.MissingPropertyException: No such property: vertex for class: Point
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
    at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetPropertySafe(AbstractCallSite.java:410)
    at com.github.eugene.kamenev.orient.graph.OrientGraphHelper.getVertexFromEntity(OrientGraphHelper.groovy:58)
```

**Comment by eugene-kamenev** [comment]
Thank you for giving a try, i will take a look soon at your use case, i have written tests only for EMBEDDED type for OrientDocument, [take a look at](https://github.com/eugene-kamenev/orientdb-groovy/blob/master/src/test/groovy/com/github/eugene/kamenev/orient/document/OrientDocumentTransformationsTest.groovy#L75) how EMBEDDED was tested. But contributions are welcome always.

**Comment by eugene-kamenev** [comment]
@dmunguia Can you make a pull request with a test that will fail, add it for vertex transform test, and we will pass this test when it will be fixed. Thanks.
